# Chapter 0: Deep Learning with Pytorch

Deep Learning is a subset of ML, ML is turning data into numbers & finding patterns in those numbers. It's about Code & Math.

1. Supervised Learning.

2. Unsupervised & Self-supervised Learning.

3. Transfer Learning.


# Chapter 1: Pytorch basics & fundamentals (with tensors & tensor operations)

In [1]:
print("Hello, I'm excited to learn Pytorch!")

Hello, I'm excited to learn Pytorch!


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## 00. Pytorch Fundamentals:

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [4]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Introduction to Tensors.

### Creating tensors.

In [5]:
# scalar: Pytorch tensors are created using ``torch.Tensors``

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 10])
vector

tensor([ 7, 10])

In [9]:
# number of square brackets
vector.ndim 

1

In [10]:
# Shape:
vector.shape

torch.Size([2])

In [11]:
# MATRIX:

MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([4, 5, 6])

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [15]:
# Tensor:

TENSOR = torch.tensor([[[1,2,3],
                                                  [3,6,9],
                                                  [10,15,20]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 15, 20]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 15, 20]])

### Create a random tensor:

Why random tensors? -> They are important because the way many NNs learn is that they start with tensors full of random numbers -> adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update`



In [19]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(1,3, 4)

random_tensor


tensor([[[0.4904, 0.9689, 0.5361, 0.6371],
         [0.2702, 0.8033, 0.3790, 0.7861],
         [0.0394, 0.3218, 0.5716, 0.9350]]])

In [20]:
random_tensor.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor:

random_image_size_tensor = torch.rand(size = (3, 224, 224))   # color channel (R, G, B), height, width 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
random_tensor = torch.rand(3,4)

### Zeros and ones Tensors

In [23]:
# Create a tensor of all zeros:

zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones:

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
random_tensor* ones

tensor([[0.4112, 0.7351, 0.2835, 0.1056],
        [0.7894, 0.0227, 0.9871, 0.1369],
        [0.9772, 0.6758, 0.9137, 0.8828]])

In [27]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors- like

In [28]:
# Use torch.range() and get deprecated message, use torch.arange()

one_to_ten = torch.arange(start = 1, end =  11, step  = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
torch.__version__

'1.12.1+cu113'

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**NOTE:** Tensor datatypes is one of the 3 big issues you'll run into with Pytorch & DeepLearning: 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: Link wiki

In [31]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                                              dtype = None,  # what data type is the tensor? e.g. float32 or float16
                                                              device = None, # "cpu", "cuda"  What device is your tensor on
                                                              requires_grad = False) # whether or not to track gradients 
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor  = float_32_tensor.type(torch.float16)

In [34]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [35]:
int_32_tensor = torch.tensor([3, 2, 9], dtype = torch.long)
int_32_tensor

tensor([3, 2, 9])

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 12., 81.])

### Getting info from tensors (tensor attributes):

1. Tensors not right datatype - ''tensor.dtype'
2. Tensors not right shape --> 'tensor.shape'
3. Tensors not on the right device  --> "tensor.device"


In [37]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.4144, 0.0329, 0.0271, 0.2020],
        [0.5377, 0.0532, 0.6134, 0.4538],
        [0.6234, 0.0432, 0.2605, 0.5171]])

In [38]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.4144, 0.0329, 0.0271, 0.2020],
        [0.5377, 0.0532, 0.6134, 0.4538],
        [0.6234, 0.0432, 0.2605, 0.5171]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [39]:
# Create a tensor and add 10 to it:

tensor = torch.tensor([1, 2, 3])
tensor  + 10

tensor([11, 12, 13])

In [40]:
# Multiply a tensor by 10
tensor = tensor * 10 
tensor

tensor([10, 20, 30])

In [41]:
# Subtract 10
tensor - 20

tensor([-10,   0,  10])

In [42]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [43]:
torch.add(tensor, 100)

tensor([110, 120, 130])

Matrix multiplication: Two main ways of performing multiplication in NN and DeepL: 

1. Element-wise
2. Matrix multiplication (dot-product)

In [44]:
# Element-wise

print(tensor ,'*', tensor)
print(f'Equals: {tensor*tensor}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [45]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(1400)

In [46]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 1.5 ms, sys: 1.11 ms, total: 2.62 ms
Wall time: 3.34 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 16 µs, total: 94 µs
Wall time: 99.7 µs


tensor(1400)

### One of the most common mistakes in DeepL


In [48]:
tensor@ tensor

tensor(1400)

**Transpose**

In [49]:
# torch.matmul(tensor_A, tensor_B.T)

### Finding the mix, max, mean, sum (tensor aggregation)

In [50]:
# Create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding positional max & min

In [55]:
# Find the position in tensor that has the min value with argmin
x[x.argmin()]

tensor(0)

In [56]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* stack: vstack or hstack
* squeeze: remove all `1` dimensions from a tensor
* unsqueeze: add a `1` dimension to a target
* permute: return a view of the input with dimensions permuted (swapped) in a certain way

In [57]:
import torch

x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [58]:
# add an extra dimension

x_reshaped = x.reshape(6, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]), torch.Size([6, 2]))

In [59]:
# change the view:
z= x.view(1,12)
z, z.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [60]:
# Changing z changes x ( because a view of a tensor shares the same memory as the original)

z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [61]:
# Stack tensors on top of each other:

x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [62]:
# torch.squeeze () - removes all single dimensions from target tensor
x_reshaped = torch.arange(1.,10.)
x_reshaped[0] = 5.

In [63]:
x_reshaped = x_reshaped.view(1,9)

In [64]:
x_reshaped.shape

torch.Size([1, 9])

In [65]:
x_reshaped.squeeze().shape

torch.Size([9])

In [66]:
# torch.unsqueeze () - adds a single dimension to a target tensor at a specific dim

In [67]:
# torch.permute()
x_ori = torch.rand(size = (224, 224, 3)) # height, width, colour channels

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_ori.permute(2,0,1) # colour channels, height, width

In [68]:
x_ori[0,0, 0] = 1234

x_ori[0, 0, 0], x_permuted[0,0,0]

(tensor(1234.), tensor(1234.))

In [69]:
# Indexing (selecting data from tensors)

# Create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)

In [70]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [71]:
# Let's index on our new tensor
x[0][0]

tensor([1, 2, 3])

In [72]:
x[:,0]

tensor([[1, 2, 3]])

### Pytorch and Numpy

Numpy is a popular scientific Python numerical computing library.

* Data in Numpy --> Pytorch tensor. `torch.from_numpy(ndarray)`

* Pytorch tensor --> Numpy `torch.Tensor.numpy()`

In [75]:
# Numpy array to tensor

import torch 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # pytorch use default float32

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [76]:
tensor.dtype

torch.float32

In [74]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [77]:
# Change the value of array, what will this do to `tensor`?

array  = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [78]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [79]:
# Tensor to NumPy array

tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
np_tensor.dtype

dtype('float32')

In [81]:
# Change the tensor, what happens to `numpy_tensor`

tensor = tensor  + 1
tensor, np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility ( trying to take random out of random)

NN works in the following mechanism: 
`start with random numbers --> tensor operations --> update random numbers to try and make better representation of the data --> again --> again...`

In [86]:
import torch

# Create two random tensors:
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A == tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
